server:
  node_id: qwen-gpu-1
security:
  internal_auth_token: "123"
asset_service:
  callback_url: https://13.60.242.64:9009/v1/vton/result
  internal_auth_token: supersecret-internal-token
  timeout: 10
  retries: 3
model:
  model_type: qwen
  model_version: 1.0.0
  device: cuda
logging:
  level: INFO
load_balancer:
  url: "http://13.60.242.64:9005"  # Your Load Balancer URL
  internal_auth_token: "YOUR_LB_SECRET"  # Optional, if LB auth enabled